spring.application.name=ByteAndBuy
game.startBonus=50
game.startMoney=300
game.minPlayersToStart=2
game.fullGroupRentMultiplier=1.5
game.workshopDiscount=0.2

spring.datasource.url=jdbc:postgresql://localhost:5432/byteandbuy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
