spring.application.name=ByteAndBuy
game.startBonus=50
game.startMoney=300
game.minPlayersToStart=2
game.fullGroupRentMultiplier=1.5
game.workshopDiscount=0.2
game.market.initialPriceMinMultiplier=0.75
game.market.initialPriceMaxMultiplier=1.25
game.market.minPriceMultiplier=0.75
game.market.maxPriceMultiplier=1.25
game.property.baseRentRate=0.1
game.property.rentForOnePropertyMultiplier=0.05

spring.datasource.url=jdbc:postgresql://localhost:5432/byteandbuy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
