spring.application.name=ByteAndBuy
game.startBonus=100
gameBuilder.startMoney=3000
game.minPlayersToStart=2
gameBuilder.fullGroupRentMultiplier=1.5
economyService.workshopDiscount=0.2
gameBuilder.initialPriceMinMultiplier=0.75
gameBuilder.initialPriceMaxMultiplier=1.25
market.marketService.minPriceMultiplier=0.75
market.marketService.maxPriceMultiplier=1.25
gameBuilder.baseRentRate=0.1
gameBuilder.rentForOnePropertyMultiplier=0.05

spring.datasource.url=jdbc:postgresql://localhost:5432/byteandbuy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
